---
swagger: 2.0
info:
  title: PayId
  description: New Payments Platform PayID API
  version: 1.0.0
paths:
  /v1/payid/register:
    post:
      description: Register customer account against a selected PayID
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/RegisterRequest'
      - name: api_key
        in: header
        required: false
        type: string
      responses:
        200:
          description: PayID Registered
          schema:
            $ref: '#/definitions/RegisterResponse'
        400:
          description: PayID Not Registered
          schema:
            $ref: '#/definitions/RegisterResponse'
      security:
      - apikey: []
  /v1/payid/contact-details:
    post:
      description: Requests the email or phone number linked to the membership
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ContactDetailsRequest'
      - name: api_key
        in: header
        required: false
        type: string
      responses:
        200:
          description: Return Contact Details
          schema:
            $ref: '#/definitions/ContactDetailsResponse'
        404:
          description: No Contact Details Found
          schema:
            $ref: '#/definitions/ContactDetailsResponse'
      security:
      - apikey: []
  /v1/payid/accounts:
    post:
      description: Get all account types linked to the membership. This list will
        filtered on the accounts that can be linked to PayID
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/AccountRequest'
      - name: api_key
        in: header
        required: false
        type: string
      responses:
        200:
          description: Return Account list
          schema:
            $ref: '#/definitions/AccountResponse'
        404:
          description: No Client Account List Found
          schema:
            $ref: '#/definitions/AccountResponse'
      security:
      - apikey: []
  /v1/payid/available:
    post:
      description: Is PayID available
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/AvailableRequest'
      - name: api_key
        in: header
        required: false
        type: string
      responses:
        200:
          description: PayID Available
          schema:
            $ref: '#/definitions/AvailableResponse'
        400:
          description: PayID Not Available
          schema:
            $ref: '#/definitions/AvailableResponse'
      security:
      - apikey: []
  /v1/payid/otp:
    post:
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/OTPRequest'
      - name: api_key
        in: header
        required: false
        type: string
      responses:
        200:
          description: Return OTP generated
          schema:
            $ref: '#/definitions/OTPResponse'
        400:
          description: OTP not generated
          schema:
            $ref: '#/definitions/OTPResponse'
      security:
      - apikey: []
definitions:
  ContactDetailsRequest:
    title: Root Type for ContactDetailsRequest
    description: The root of the ContactDetailsRequest type's schema.
    required:
    - api
    - _api
    type: object
    properties:
      _api:
        $ref: '#/definitions/MobileApiData'
        description: Mobile API Data
  AccountRequest:
    title: Root Type for ContactDetailsRequest
    description: The root of the ContactDetailsRequest type's schema.
    required:
    - api
    - _api
    type: object
    properties:
      _api:
        $ref: '#/definitions/MobileApiData'
        description: Mobile API Data
  MobileApiData:
    title: Root Type for MobileApi
    description: The root of the MobileApi type's schema.
    type: object
    properties:
      deviceID:
        description: The unique Device Id
        type: string
      customerID:
        description: The customer ID
        type: string
      nonce:
        description: Nonce token to control session
        type: string
      hostVersion:
        format: int32
        description: The version of the Host Worker Process that this api request
          is configured to communicate with
        type: integer
      sessionID:
        description: Unique Authorised Session Identifier
        type: string
      appVersion:
        format: int32
        description: Unique Number Identifier representing what internal version of
          the App is requesting
        type: integer
      timestamp:
        description: Device Timestamp - mobile device may have wrong datetime
        type: string
      requestID:
        description: Mobile API Request ID for tracing
        type: string
  AccountResponse:
    title: Root Type for FasterPayAccountResponse
    description: The root of the FasterPayAccountResponse type's schema.
    type: object
    properties:
      statusMessage:
        description: System status message
        type: string
      statusCode:
        description: System status code
        type: integer
      accounts:
        description: List of Accounts
        type: array
        items:
          $ref: '#/definitions/Account'
      payids:
        description: List of PayID's
        type: array
        items:
          $ref: '#/definitions/PayID'
  ContactDetailsResponse:
    title: Root Type for ContactDetailsResponse
    description: The root of the ContactDetailsResponse type's schema.
    type: object
    properties:
      statusMessage:
        description: System status message
        type: string
      emails:
        description: List of email addresses
        type: array
        items:
          $ref: '#/definitions/EmailAddress'
      mobiles:
        description: List of mobile numbers
        type: array
        items:
          $ref: '#/definitions/MobileNumber'
      statusCode:
        description: System status code
        type: integer
  RegisterResponse:
    title: Root Type for RegisterRequestResponse
    description: The root of the RegisterRequestResponse type's schema.
    type: object
    properties:
      statusMessage:
        description: System status message
        type: string
      statusCode:
        description: 'System status code '
        type: integer
  AvailableRequest:
    title: Root Type for RegisterRequest
    description: The root of the RegisterRequest type's schema.
    required:
    - Account
    - api
    - _api
    - PayID
    - PayIDType
    - ShortName
    - payIdAccountData
    type: object
    properties:
      _api:
        $ref: '#/definitions/MobileApiData'
        description: Mobile API Data
      payIDAlias:
        type: string
      payIDType:
        type: string
  AvailableResponse:
    title: Root Type for RegisterRequestResponse
    description: The root of the RegisterRequestResponse type's schema.
    type: object
    properties:
      statusMessage:
        description: System status message
        type: string
      statusCode:
        description: 'System status code '
        type: integer
  Account:
    title: Root Type for Account
    description: The root of the Account type's schema.
    type: object
    properties:
      customer:
        format: int32
        type: integer
      accountType:
        type: string
      accountName:
        type: string
      accountNickname:
        type: string
      balance:
        format: int32
        type: integer
      availableBalance:
        format: int32
        type: integer
      bsb:
        type: string
      signatories:
        format: int32
        type: integer
  EmailAddress:
    title: Root Type for EmailAddress
    description: The root of the EmailAddress type's schema.
    type: object
    properties:
      emailAddress:
        type: string
  MobileNumber:
    title: Root Type for MobileNumber
    description: The root of the MobileNumber type's schema.
    type: object
    properties:
      mobileNumber:
        type: string
  PayID:
    title: Root Type for PayID
    description: The root of the PayID type's schema.
    type: object
    properties:
      payIDAlias:
        type: string
      payIDType:
        type: string
      toAccountCode:
        type: string
      payIDStatus:
        type: string
  OTPRequest:
    title: Root Type for ContactDetailsRequest
    description: The root of the ContactDetailsRequest type's schema.
    required:
    - api
    - _api
    - payIDAlias
    - payIDType
    - toAccountCodes
    - shortName
    type: object
    properties:
      _api:
        $ref: '#/definitions/MobileApiData'
        description: Mobile API Data
      payIDAlias:
        type: string
      payIDType:
        type: string
      toAccountCodes:
        type: string
      shortName:
        type: string
  OTPResponse:
    title: Root Type for RegisterRequestResponse
    description: The root of the RegisterRequestResponse type's schema.
    type: object
    properties:
      statusMessage:
        description: System status message
        type: string
      statusCode:
        description: System status code
        type: integer
  RegisterRequest:
    title: Root Type for RegisterRequest
    description: The root of the RegisterRequest type's schema.
    required:
    - _api
    type: object
    properties:
      payIDAlias:
        description: Mobile Number  Or  Email Address
        type: string
      payIDType:
        description: 4 letter code to indicate alias type (ASL Codes)
        type: string
      toAccountCodes:
        description: 'Full account type code '
        type: string
      shortName:
        description: Shortname that will be used by
        type: string
      otp:
        description: "\t Encrypted six digit verification code "
        type: string
      termConditionsVersion:
        description: Last Updated date for T&Cs
        type: string
      _api:
        $ref: '#/definitions/MobileApiData'
        description: Mobile API Data
securityDefinitions:
  apikey:
    type: apiKey
    description: Auth User API Key
    name: api_key
    in: header
